compiler: clang
sudo: false

matrix:
  include:
    - os: linux
    - os: osx

notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    - NODE_VERSION=0.12
    - JANKY_BRANCH=stable
    - npm_config_runtime=electron

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
  - ./script/add-key
  - export JANKY_SHA1=`git rev-parse --short HEAD`
  - source .atomrc

script:
  - ./script/build
  # - ./script/run-ci-specs

after_script: ./script/remove-key

cache:
  directories:
    - build/node_modules
    - dist/atom-work-dir/node_modules

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
